# Set PATH, MANPATH, etc., for Homebrew
if [[ -d "/opt/homebrew/bin" ]]; then
    export HOMEBREW_PREFIX="/opt/homebrew";
    export HOMEBREW_CELLAR="/opt/homebrew/Cellar";
    export HOMEBREW_REPOSITORY="/opt/homebrew";
    export PATH="/opt/homebrew/bin:/opt/homebrew/sbin${PATH+:$PATH}";
    export MANPATH="/opt/homebrew/share/man${MANPATH+:$MANPATH}:";
    export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}";
fi

# Add Python packages to PATH
if [[ -d "$HOME/Library/Python/3.9/bin" ]];then
    export PATH="$HOME/Library/Python/3.9/bin:$PATH"
fi

# PDM PEP582
if [[ -x "$HOME/Library/Application Support/pdm/venv/bin/pdm" ]]; then
    if [[ -n "$PYTHONPATH" ]]; then
        export PYTHONPATH="$HOME/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/pep582:$PYTHONPATH"
    else
        export PYTHONPATH="$HOME/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/pep582"
    fi
fi

# Load user defined functions
if [[ -d "${ZDOTDIR:-$HOME}/.functions" ]]; then
    export FPATH="${ZDOTDIR:-$HOME}/.functions${FPATH+:$FPATH}"
fi
