# Set zsh history file format
export HISTFILE="$ZDOTDIR/.zsh_history"
export HISTTIMEFORMAT="[%F %T] "

# Setup the gpg-agent for SSH authentication
export GPG_TTY="$(tty)"
export SSH_AUTH_SOCK="$(/opt/homebrew/bin/gpgconf --list-dirs agent-ssh-socket)"
/opt/homebrew/bin/gpgconf --launch gpg-agent
