# Setup the gpg-agent for SSH authentication
unset SSH_AGENT_PID
if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
  export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
fi
export GPG_TTY=$(tty)
gpg-connect-agent updatestartuptty /bye >/dev/null

# Set PATH, MANPATH, etc., for Homebrew
if [ -d "/opt/homebrew/bin" ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# Set PATH for Python
if [ -d "$HOME/Library/Python/3.9/bin" ]; then
    export PATH="$HOME/Library/Python/3.9/bin:$PATH"
fi

# source "$HOME/.cargo/env"

# PEP582
if command -v pdm >/dev/null 2>&1; then
    if [ -n "$PYTHONPATH" ]; then
        export PYTHONPATH="$HOME/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/pep582:$PYTHONPATH"
    else
        export PYTHONPATH="$HOME/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/pep582"
    fi
fi

# Set zsh history file
HISTFILE="${ZDOTDIR:-$HOME}/.zsh_history"
HISTTIMEFORMAT="[%F %T] "
HISTSIZE=1000000
SAVEHIST=100000

# Configure auto suggestions
ZSH_AUTOSUGGEST_STRATEGY=(match_prev_cmd completion)
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
ZSH_AUTOSUGGEST_COMPLETION_IGNORE="git *"
