# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Load options
source $ZDOTDIR/.options

# Load functions
source $ZDOTDIR/.functions

# Load aliases
source $ZDOTDIR/.aliases

# Load Zi
if [[ -r "${XDG_CONFIG_HOME:-${HOME}/.config}/zi/init.zsh" ]]; then
  source "${XDG_CONFIG_HOME:-${HOME}/.config}/zi/init.zsh" && zzinit
fi

autoload -Uz _zi
(( ${+_comps} )) && _comps[zi]=_zi

# Load plugins without Turbo
zi for \
    agkozak/zsh-z

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zi light-mode for \
    z-shell/z-a-meta-plugins \
    @annexes \
    @romkatv \
    @z-shell \
    @zsh-users+fast

zi wait lucid as"completion" for \
    blockf \
        zchee/zsh-completions \
    OMZP::docker/_docker \
    OMZP::docker-compose/_docker-compose

# Load a few useful plugins for zsh with Turbo
zi wait lucid for \
    OMZP::colored-man-pages \
    OMZP::command-not-found \
    OMZP::sudo \
    OMZP::git \
    OMZL::git.zsh

zi wait lucid for \
    skip"fd bat hexyl hyperfine vivid exa ripgrep" \
        @console-tools

zi wait lucid for \
    @py-utils

zi wait pack atload=+"zicompinit_fast; zicdreplay" for \
    system-completions \
    brew-completions

# ### End of Zi's installer chunk

# Load colors
autoload -U colors
colors

autoload -U bashcompinit
bashcompinit

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
